corpus:
  # PDFs referenced by JSON are assumed in same directory
  include: "PDFs/include/include_new.json"
  exclude: "PDFs/exclude/exclude_new.json"
model:
  save_loc: "new_test.pt" # if training a new model
  #pretrained: "model.pt" # if loading a pretrained model
strategy:
  name: svm
  vector_type: tf-idf