corpus:
  from_zotero: True # if True uses zotero collections, and expects a zotero config
  zotero_config: "config/zotero.yaml"
  save_loc: "ethiopia_corpus.pkl"
  test_labels: True # whether or not the test data has labels (for printing accuracy on predictions)
  # If loading from existing Corpus or crawl JSON
  #load_saved: "corpus.pkl"
  # PDFs referenced by JSON are assumed in same directory. If there is more than one json, pipe delimit them |
  include: "PDFs/include/include_new.json"
  exclude: "PDFs/exclude/exclude_new.json"
model:
  #save_loc: "new_test.pt" # if training a new model
  pretrained: "new_test.pt" # if loading a pretrained model
strategy:
  # for clarification, see sklearn docs, particularly for SVM options: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDClassifier.html
  name: svm # svm is the only one supported at present
  vector_type: tf-idf #
  max_iter: 1000 # truncates early stopping even if
  loss: log # log, hinge, squared_hinge, modified_huber, perceptron
  regularizer: l2 # l2, l1, elasticnet
  lr: optimal # optimal, adaptive
  early_stopping: True # bool
  balance_classes: True # bool, if yes adjusts class weights to account for imbalance