corpus:
  test_labels: False # whether or not the test data has labels (for printing accuracy on predictions)
  load_saved: "production_corpus.pkl"
model:
  pretrained: "production_classifier.pt" # if loading a pretrained model
classify:
  confidence_threshold: False # bool
  threshold: 2.5 # float, maximum acceptable distance from decision boundary. Ignored if confidence_threshold is False