mode: read # mode is either read or write. Write is where info is written to a csv in order to use it for humans to label, Read is where we read the results back

read_mode:
  csv_path: PDFs/new_training_data/Tanzania_scopus_complete.csv
